"""
Regenerate motion-lab-catalog.json: movement-aligned YouTube IDs + i.ytimg thumbnails.
"""
import json
from pathlib import Path

# pick_key() -> instructional video id (embed-friendly)
Y = {
    "back_squat": "gcNh17Ckjgg",
    "front_squat": "qmkjkGmB3v4",
    "goblet": "Me9i5Old7oQ",
    "box_squat": "qyOelMdM4og",
    "pause_squat": "gcNh17Ckjgg",
    "oh_squat": "qSOQhZy0zH8",
    "zercher": "OZruu0MuF7A",
    "hack_squat": "3wNd9Vg6g4A",
    "leg_press": "3wNd9Vg6g4A",
    "leg_ext": "T8vLb1YU2Ps",
    "sissy": "gcNh17Ckjgg",
    "walking_lunge": "QFZ4q2jDUyY",
    "reverse_lunge": "QFZ4q2jDUyY",
    "curtsy": "QFZ4q2jDUyY",
    "bulgarian": "2K2Wm7Z8Yc",
    "step_up": "QFZ4q2jDUyY",
    "cossack": "gcNh17Ckjgg",
    "wall_sit": "gcNh17Ckjgg",
    "deadlift": "ZaTM37cfiDs",
    "sumo_dl": "ZaTM37cfiDs",
    "rdl": "jEy_czb3RKA",
    "sldl": "jEy_czb3RKA",
    "trap_bar": "ZaTM37cfiDs",
    "rack_pull": "ZaTM37cfiDs",
    "good_morning": "ytGaGWC_3WQ",
    "hip_thrust": "xDmFk_JWGfg",
    "glute_bridge": "xDmFk_JWGfg",
    "cable_pull": "L2g0jxZFXow",
    "nordic": "NBY9-kTuohk",
    "leg_curl": "pI65w6ebY9g",
    "calf": "gwLzBJYoWlI",
    "tibialis": "gwLzBJYoWlI",
    "donkey_calf": "gwLzBJYoWlI",
    "seated_calf": "gwLzBJYoWlI",
    "farmer": "tpqdbnCjzZ4",
    "bench": "vcBig73ojpE",
    "close_grip": "vcBig73ojpE",
    "incline_bench": "YaXPRqUwItQ",
    "decline_bench": "vcBig73ojpE",
    "db_bench": "vcBig73ojpE",
    "incline_db": "YaXPRqUwItQ",
    "arnold": "gvmhug-SdBY",
    "shoulder_press": "g3du8q1Yn8k",
    "machine_chest": "vcBig73ojpE",
    "crossover": "IODxDxX7oi4",
    "pec_deck": "IODxDxX7oi4",
    "pushup": "Ahdu_UdZul4",
    "diamond_push": "Ahdu_UdZul4",
    "wide_push": "Ahdu_UdZul4",
    "archer_push": "Ahdu_UdZul4",
    "ring_dip": "yN6Q1QWdNnA",
    "parallel_dip": "yN6Q1QWdNnA",
    "chest_dip": "yN6Q1QWdNnA",
    "pullup": "eDP_CH--eJc",
    "chinup": "brhRxr6FhAs",
    "neutral_pull": "eDP_CH--eJc",
    "lat_pull": "sY9T_dHDxNM",
    "straight_arm": "sY9T_dHDxNM",
    "row_bb": "FWJR5Ve8bnQ",
    "cable_row": "roCP6wCXPqo",
    "tbar": "FWJR5Ve8bnQ",
    "pendlay": "FWJR5Ve8bnQ",
    "single_arm_row": "FWJR5Ve8bnQ",
    "meadows": "FWJR5Ve8bnQ",
    "face_pull": "HSoHeSjvId4",
    "rear_delt": "3VcKaXpzqRo",
    "lateral_raise": "3VcKaXpzqRo",
    "front_raise": "3VcKaXpzqRo",
    "upright_row": "n6RjOx7UGV4",
    "shrug": "n6RjOx7UGV4",
    "curl": "vB5OhOL872M",
    "hammer": "vB5OhOL872M",
    "preacher": "vB5OhOL872M",
    "skull": "d_KZxkYJ0VQ",
    "ote": "nRiJVZDpdL0",
    "tricep_pd": "nRiJVZDpdL0",
    "rope_pd": "nRiJVZDpdL0",
    "single_pd": "nRiJVZDpdL0",
    "kickback": "nRiJVZDpdL0",
    "plank": "pSHjTRCQ8Iw",
    "side_plank": "pSHjTRCQ8Iw",
    "dead_bug": "DJQim2lqc8k",
    "bird_dog": "DJQim2lqc8k",
    "ab_wheel": "ghDQdDjw214",
    "hanging_leg": "ghDQdDjw214",
    "knee_raise": "ghDQdDjw214",
    "russian": "nmwgirgXLYM",
    "woodchop": "nmwgirgXLYM",
    "pallof": "nmwgirgXLYM",
    "mountain": "dZgVxmfkXuM",
    "burpee": "dZgVxmfkXuM",
    "jump_squat": "xqvCmoiphqM",
    "box_jump": "NBY9-kTuohk",
    "kb_swing": "1cVT3ee9mgU",
    "battle_rope": "pI65w6ebY9g",
    "assault_bike": "1BZM2Vre5oc",
    "rowing_erg": "tr--Hz0Ij2M",
    "jump_rope": "1BZM2Vre5oc",
    "high_knee": "dZgVxmfkXuM",
    "butt_kick": "dZgVxmfkXuM",
    "bear": "dZgVxmfkXuM",
    "tgu": "1cVT3ee9mgU",
    "muscle_up": "eDP_CH--eJc",
    "lsit": "eDP_CH--eJc",
    "handstand": "eDP_CH--eJc",
    "wall_walk": "eDP_CH--eJc",
    "air_squat": "gcNh17Ckjgg",
    "dip": "yN6Q1QWdNnA",
    "ohp": "g3du8q1Yn8k",
    "mobility": "5b7f7vQZJ8Y",
    "stretch": "tr--Hz0Ij2M",
    "olympic": "JwiWIZPJv-c",
    "power_clean": "JwiWIZPJv-c",
    "hang_clean": "JwiWIZPJv-c",
    "push_press": "g3du8q1Yn8k",
    "push_jerk": "JwiWIZPJv-c",
    "split_jerk": "JwiWIZPJv-c",
    "snatch_high": "JwiWIZPJv-c",
    "pigeon": "tr--Hz0Ij2M",
    "couch": "tr--Hz0Ij2M",
    "9090": "Lq1l8Y6uQ0A",
    "world": "5b7f7vQZJ8Y",
    "ankle": "Lq1l8Y6uQ0A",
    "thoracic": "yR8sYUvYj9E",
    "band_pull": "HSoHeSjvId4",
    "scapular": "HSoHeSjvId4",
    "arm_circle": "5b7f7vQZJ8Y",
    "leg_swing": "Lq1l8Y6uQ0A",
    "hip_circle": "Lq1l8Y6uQ0A",
    "cat_cow": "ASdvN_XEl_c",
}

LABEL = "YouTube (privacy-enhanced embed)"


def pick_key(title: str) -> str:
    t = title.lower().replace("’", "'")
    pairs = [
        ("barbell back squat", "back_squat"),
        ("front squat", "front_squat"),
        ("goblet squat", "goblet"),
        ("box squat", "box_squat"),
        ("pause squat", "pause_squat"),
        ("overhead squat", "oh_squat"),
        ("zercher squat", "zercher"),
        ("hack squat", "hack_squat"),
        ("leg press", "leg_press"),
        ("leg extension", "leg_ext"),
        ("sissy squat", "sissy"),
        ("walking lunge", "walking_lunge"),
        ("reverse lunge", "reverse_lunge"),
        ("curtsy lunge", "curtsy"),
        ("bulgarian split squat", "bulgarian"),
        ("step-up", "step_up"),
        ("cossack squat", "cossack"),
        ("wall sit", "wall_sit"),
        ("conventional deadlift", "deadlift"),
        ("sumo deadlift", "sumo_dl"),
        ("romanian deadlift", "rdl"),
        ("stiff-leg deadlift", "sldl"),
        ("trap bar deadlift", "trap_bar"),
        ("rack pull", "rack_pull"),
        ("good morning", "good_morning"),
        ("barbell hip thrust", "hip_thrust"),
        ("glute bridge", "glute_bridge"),
        ("single-leg rdl", "rdl"),
        ("cable pull-through", "cable_pull"),
        ("nordic ham curl", "nordic"),
        ("seated leg curl", "leg_curl"),
        ("lying leg curl", "leg_curl"),
        ("standing calf raise", "calf"),
        ("seated calf raise", "seated_calf"),
        ("donkey calf raise", "donkey_calf"),
        ("tibialis raise", "tibialis"),
        ("farmer carry", "farmer"),
        ("suitcase carry", "farmer"),
        ("overhead carry", "farmer"),
        ("barbell bench press", "bench"),
        ("close-grip bench", "close_grip"),
        ("incline barbell bench", "incline_bench"),
        ("decline bench press", "decline_bench"),
        ("dumbbell bench press", "db_bench"),
        ("incline dumbbell press", "incline_db"),
        ("arnold press", "arnold"),
        ("dumbbell shoulder press", "shoulder_press"),
        ("machine chest press", "machine_chest"),
        ("cable crossover", "crossover"),
        ("incline cable fly", "crossover"),
        ("pec deck fly", "pec_deck"),
        ("push-up", "pushup"),
        ("diamond push-up", "diamond_push"),
        ("wide push-up", "wide_push"),
        ("archer push-up", "archer_push"),
        ("ring dip", "ring_dip"),
        ("parallel bar dip", "parallel_dip"),
        ("chest dip", "chest_dip"),
        ("pull-up", "pullup"),
        ("chin-up", "chinup"),
        ("neutral-grip pull-up", "neutral_pull"),
        ("lat pulldown", "lat_pull"),
        ("straight-arm pulldown", "straight_arm"),
        ("chest-supported row", "row_bb"),
        ("cable row", "cable_row"),
        ("seated cable row", "cable_row"),
        ("t-bar row", "tbar"),
        ("pendlay row", "pendlay"),
        ("single-arm dumbbell row", "single_arm_row"),
        ("meadows row", "meadows"),
        ("face pull", "face_pull"),
        ("rear delt fly", "rear_delt"),
        ("cable lateral raise", "lateral_raise"),
        ("dumbbell lateral raise", "lateral_raise"),
        ("front raise", "front_raise"),
        ("upright row", "upright_row"),
        ("shrug", "shrug"),
        ("barbell curl", "curl"),
        ("dumbbell curl", "curl"),
        ("hammer curl", "hammer"),
        ("preacher curl", "preacher"),
        ("cable curl", "curl"),
        ("skull crusher", "skull"),
        ("overhead tricep extension", "ote"),
        ("tricep pushdown", "tricep_pd"),
        ("rope pushdown", "rope_pd"),
        ("single-arm pushdown", "single_pd"),
        ("cable kickback", "kickback"),
        ("plank", "plank"),
        ("side plank", "side_plank"),
        ("dead bug", "dead_bug"),
        ("bird dog", "bird_dog"),
        ("ab wheel rollout", "ab_wheel"),
        ("hanging leg raise", "hanging_leg"),
        ("knee raise", "knee_raise"),
        ("russian twist", "russian"),
        ("cable woodchop", "woodchop"),
        ("pallof press", "pallof"),
        ("mountain climber", "mountain"),
        ("burpee", "burpee"),
        ("jump squat", "jump_squat"),
        ("box jump", "box_jump"),
        ("kettlebell swing", "kb_swing"),
        ("battle ropes", "battle_rope"),
        ("assault bike", "assault_bike"),
        ("rowing machine", "rowing_erg"),
        ("jump rope", "jump_rope"),
        ("high knees", "high_knee"),
        ("butt kicks", "butt_kick"),
        ("bear crawl", "bear"),
        ("turkish get-up", "tgu"),
        ("muscle-up", "muscle_up"),
        ("l-sit", "lsit"),
        ("handstand hold", "handstand"),
        ("wall walk", "wall_walk"),
        ("air squat", "air_squat"),
        ("bodyweight squat jump", "air_squat"),
        ("cat-cow", "cat_cow"),
        ("world greatest stretch", "world"),
        ("90/90 hip stretch", "9090"),
        ("pigeon stretch", "pigeon"),
        ("couch stretch", "couch"),
        ("ankle mobility drill", "ankle"),
        ("thoracic extension", "thoracic"),
        ("band pull-apart", "band_pull"),
        ("scapular wall slide", "scapular"),
        ("arm circles", "arm_circle"),
        ("leg swings", "leg_swing"),
        ("hip circles", "hip_circle"),
        ("snatch grip high pull", "snatch_high"),
        ("power clean", "power_clean"),
        ("hang clean", "hang_clean"),
        ("push press", "push_press"),
        ("push jerk", "push_jerk"),
        ("split jerk", "split_jerk"),
    ]
    for phrase, key in pairs:
        if phrase in t:
            return key
    return "bench"


def main() -> None:
    root = Path(__file__).resolve().parents[1]
    src = root / "src/main/resources/static/data/motion-lab-catalog.json"
    data = json.loads(src.read_text(encoding="utf-8"))
    for row in data:
        key = pick_key(row["title"])
        yt = Y[key]
        row["youtubeId"] = yt
        row["thumbUrl"] = f"https://i.ytimg.com/vi/{yt}/hqdefault.jpg"
        row["videoLabel"] = LABEL
        for k in ("mediaUrl", "mediaKind", "gif"):
            row.pop(k, None)
    src.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")
    print("Wrote", len(data), "rows to", src)


if __name__ == "__main__":
    main()
